# Site settings
name: Eric Ferber
title: Eric Ferber
email: eric@atelier-ferber.fr
description: "Eric Ferber - Sculpteur monumental"
baseurl: ""
url: "http://eric-ferber.github.io/"

# Build settings
markdown: kramdown
permalinks: pretty

exclude: [LICENSE, README.md, Rakefile, bootstrap/less, node_modules]

galleryDefaultSettings:

    imgDefaultExtension: .jpg
    imgDefaultThumbAppendString: -75
    imgDefaultFormats:
        500: -500

    imgAltAppendString: ' - Eric Ferber'
