# Site settings
name: Eric Ferber - Sculpteur
title: Eric Ferber - Sculpteur
email: eric@atelier-ferber.fr
description: "Eric Ferber - Sculpteur monumental"
baseurl: ""
url: "http://eric-ferber.github.io/"

# Build settings
markdown: kramdown
permalinks: pretty


exclude: [bootstrap/less]
